export const constituencies = [
  "Chobe",
  "Maun east",
  "Maun west",
  "Ngami",
  "Okavango",
  "Tati east",
  "Tati west",
  "Francistown east",
  "Francistown south",
  "Francistown west",
  "Nata-gweta",
  "Nkange",
  "Shashe west",
  "Tonota",
  "Bobonong",
  "Mmadinare",
  "Selibe phikwe east",
  "Selibe phikwe west",
  "Lerala-maunatlala",
  "Palapye",
  "Sefhare-ramokgonami",
  "Mahalapye east",
  "Mahalapye west",
  "Shoshong",
  "Serowe north",
  "Serowe west",
  "Serowe south",
  "Boteti east",
  "Boteti west",
  "Mochudi east",
  "Mochudi west",
  "Gaborone central",
  "Gaborone north",
  "Gaborone south",
  "Gaborone bonnington north",
  "Gaborone bonnington south",
  "Tlokweng",
  "Ramotswa",
  "Mogoditshane",
  "Gabane-mmankgodi",
  "Thamaga-kumakwane",
  "Molepolole north",
  "Molepolole south",
  "Lentsweletau-mmopane",
  "Letlhakeng lephephe",
  "Takatokwane",
  "Lobatse",
  "Goodhope mabule",
  "Mmathethe-molapowabojang",
  "Kanye north",
  "Kanye south",
  "Moshupa-manyana",
  "Jwaneng-mabutsane",
  "Kgalagadi north",
  "Kgalagadi south",
  "Ghanzi north",
  "Ghanzi south",
];
